# Generated by Django 5.0.2 on 2024-02-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0002_userprofile_contributions_userprofile_interests_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
