# Generated by Django 5.0.2 on 2024-03-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='creator',
        ),
    ]
