# Generated by Django 5.0.2 on 2024-03-02 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_project_end_date_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 2, 14, 48, 35, 450328)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 2, 14, 48, 35, 450328)),
        ),
    ]
