# Generated by Django 5.0.2 on 2024-03-13 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_project_end_date_alter_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='creator',
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 13, 21, 25, 47, 570692)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 13, 21, 25, 47, 570692)),
        ),
    ]
