# Generated by Django 5.0.2 on 2024-03-13 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_alter_project_end_date_alter_project_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='participants',
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 13, 22, 24, 3, 663345)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 13, 22, 24, 3, 663345)),
        ),
    ]
